In [ ]:
# Import all the Neccessary Libraries
import pandas as pd

from pathlib import Path

input_file_path = Path.cwd() / "processed files" / "netflix_india_yt_data.csv"
# Load the Netflix India Youtube Video csv File Into Pandas dataframe
df = pd.read_csv(input_file_path)
# Display First Five Rows 
df.head(5)

,video_id,published_date,like_count,view_count,comment_count,tags_count,duration_minutes,video_length_bucket,weekday
0,KQ2a4uawQBo,2024-12-20,7111.0,52864,394.0,19,1.18,Short,Friday
1,bOR7S0j_wq8,2024-12-19,642.0,44300,30.0,23,3.03,Short,Thursday
2,GRM8Q-1fVJ0,2024-12-19,3300.0,201087,101.0,30,1.25,Short,Thursday
3,b0b8WBglCHo,2024-12-18,354.0,19642,25.0,20,1.73,Short,Wednesday
4,QCPOl_7cdnQ,2024-12-18,3455.0,117292,130.0,20,1.68,Short,Wednesday

# Question 2 : How many valid video IDs have surpassed 1 million views on the channel?

In [7]:
df[(df['view_count'] > 1000000)]['video_id'].drop_duplicates().count()

1231

In [17]:
new_df = df[(df['view_count'] > 1000000)]

new_df1 =new_df[(new_df['video_id'] == "#NAME?")]

new_df1.head()

,video_id,published_date,like_count,view_count,comment_count,tags_count,duration_minutes,video_length_bucket,weekday
221,#NAME?,2024-10-08,40917.0,2649349,1007.0,14,3.52,Short,Tuesday
508,#NAME?,2024-07-16,175171.0,4027234,405.0,21,0.77,Short,Tuesday
566,#NAME?,2024-06-27,23562.0,2057933,341.0,24,2.27,Short,Thursday
996,#NAME?,2024-02-29,14652.0,4945334,230.0,3,1.22,Short,Thursday
1535,#NAME?,2023-08-16,54222.0,2458722,2342.0,3,1.97,Short,Wednesday

In [16]:
len(new_df) - len(new_df1)

1230